---

- hosts: bpi
  become: yes

  tasks:

    - name: remove shell from pi user
      user:
        name: pi
        shell: /usr/sbin/nologin

#    - name: remove user pi
#      user:
#        name: pi
#        state: absent

    - name: remove shell from root user
      user:
        name: root
        shell: /usr/sbin/nologin


#    - name: remove old docker packages
#      apt: "name={{item}} state=absent"
#      with_items:
#        - docker
#        - docker-engine
#        - docker.io

#    - name: install apt packages for https
#      apt: "name={{item}} state=present"
#      with_items:
#        - apt-transport-https
#        - ca-certificates
#        - curl
#        - software-properties-common

#    - name: download repo key
#      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /tmp/docker-key

#    - name: add key
#      command: apt-key add /tmp/docker-key

#    - name: install repo
#      command: add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/ubuntu xenial stable"

#    - name: install docker
#      apt: update_cache=yes name=docker-ce state=present

    - name: install minidvla
      apt: name=minidlna state=present

    - name: Mount up device by label
      mount:
        path: /backup/
        src: /dev/sdb1
        fstype: ext4
        state: mounted
        
    - name: copy minidnla config
      copy: src=minidlna.conf dest=/etc/minidlna.conf

    - name: setup systemd
      systemd: name=minidlna state=started enabled=true

    - name: copy file to disable power management on wifi
      copy: src=wifi-disable-power-management dest=/etc/network/if-up.d/
